In [22]:
import numpy as np

In [23]:
A = np.array([[0, 1], [2, 3], [4, 5]])

In [24]:
#多次元配列Aの作成
A=np.array([[0,1],[2,3],[4,5]])
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [25]:
#多次元配列Bの作成
B=np.array([[0,1,2,3],[4,5,6,7]])
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [26]:
#行列の積の計算
C=np.dot(A,B)
C

array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47]])

In [27]:
np.max(C)

np.int64(47)